// Generated by scripts/sync-upstream-schemas.mjs from cua-driver 0.28.2. Do not edit by hand.
export const UPSTREAM_DRIVER_VERSION = "0.28.2";

export const UPSTREAM_SCHEMAS: Readonly<Record<string, Record<string, unknown>>> = {
  "bring_to_front": {
    "additionalProperties": false,
    "properties": {
      "pid": {
        "type": "integer"
      },
      "window_id": {
        "type": "integer"
      }
    },
    "required": [
      "pid"
    ],
    "type": "object"
  },
  "browser_click": {
    "additionalProperties": true,
    "properties": {
      "input_route": {
        "description": "\"trusted\" (default): Input.dispatchMouseEvent.",
        "enum": [
          "trusted",
          "dom_event"
        ],
        "type": "string"
      },
      "ref": {
        "description": "Page element ref in the p<snapshot>:<index> namespace from get_browser_state.",
        "type": "string"
      },
      "session": {
        "description": "For multi-call work, prefer a short public session label and repeat it on every call that accepts it.",
        "type": "string"
      },
      "tab_id": {
        "description": "Opaque tab id from get_browser_state (session-scoped).",
        "type": "string"
      },
      "target_id": {
        "description": "Opaque browser target id minted by get_browser_state (session-scoped; never a CDP id).",
        "type": "string"
      },
      "x": {
        "description": "Viewport x (CSS px) — alternative to ref.",
        "type": "number"
      },
      "y": {
        "description": "Viewport y (CSS px) — alternative to ref.",
        "type": "number"
      }
    },
    "required": [
      "target_id",
      "tab_id"
    ],
    "type": "object"
  },
  "browser_dialog": {
    "additionalProperties": true,
    "properties": {
      "action": {
        "enum": [
          "inspect",
          "accept",
          "dismiss"
        ],
        "type": "string"
      },
      "delivery_mode": {
        "default": "background",
        "description": "Requested foreground posture for accept/dismiss.",
        "enum": [
          "background",
          "foreground"
        ],
        "type": "string"
      },
      "dialog_id": {
        "description": "Opaque current dialog generation returned by action=inspect.",
        "type": "string"
      },
      "prompt_text": {
        "description": "Sensitive response text, valid only when accepting a prompt dialog.",
        "type": "string"
      },
      "session": {
        "description": "For multi-call work, prefer a short public session label and repeat it on every call that accepts it.",
        "type": "string"
      },
      "tab_id": {
        "description": "Opaque tab id from get_browser_state (session-scoped).",
        "type": "string"
      },
      "target_id": {
        "description": "Opaque browser target id minted by get_browser_state (session-scoped; never a CDP id).",
        "type": "string"
      }
    },
    "required": [
      "target_id",
      "tab_id",
      "action"
    ],
    "type": "object"
  },
  "browser_download": {
    "additionalProperties": true,
    "properties": {
      "destination_root": {
        "description": "Absolute, existing, canonical directory approved to receive the download.",
        "type": "string"
      },
      "ref": {
        "description": "Live page ref whose activation initiates the download.",
        "type": "string"
      },
      "session": {
        "description": "For multi-call work, prefer a short public session label and repeat it on every call that accepts it.",
        "type": "string"
      },
      "tab_id": {
        "description": "Opaque exact tab id from get_browser_state.",
        "type": "string"
      },
      "target_id": {
        "description": "Opaque exact browser target id from get_browser_state.",
        "type": "string"
      }
    },
    "required": [
      "session",
      "target_id",
      "tab_id",
      "ref",
      "destination_root"
    ],
    "type": "object"
  },
  "browser_navigate": {
    "additionalProperties": true,
    "properties": {
      "session": {
        "description": "For multi-call work, prefer a short public session label and repeat it on every call that accepts it.",
        "type": "string"
      },
      "tab_id": {
        "description": "Opaque tab id from get_browser_state (session-scoped).",
        "type": "string"
      },
      "target_id": {
        "description": "Opaque browser target id minted by get_browser_state (session-scoped; never a CDP id).",
        "type": "string"
      },
      "url": {
        "description": "Destination URL (http:, https:, or about:).",
        "type": "string"
      }
    },
    "required": [
      "target_id",
      "tab_id",
      "url"
    ],
    "type": "object"
  },
  "browser_pointer": {
    "additionalProperties": true,
    "properties": {
      "action": {
        "enum": [
          "hover",
          "right_click",
          "double_click",
          "scroll",
          "drag"
        ],
        "type": "string"
      },
      "delta_x": {
        "description": "Horizontal scroll delta in CSS pixels.",
        "type": "number"
      },
      "delta_y": {
        "description": "Vertical scroll delta in CSS pixels.",
        "type": "number"
      },
      "destination_ref": {
        "description": "Drag destination page ref in the exact same frame.",
        "type": "string"
      },
      "input_route": {
        "default": "trusted",
        "enum": [
          "trusted",
          "dom_event"
        ],
        "type": "string"
      },
      "ref": {
        "description": "Origin page ref.",
        "type": "string"
      },
      "session": {
        "description": "For multi-call work, prefer a short public session label and repeat it on every call that accepts it.",
        "type": "string"
      },
      "tab_id": {
        "description": "Opaque tab id minted by get_browser_state.",
        "type": "string"
      },
      "target_id": {
        "description": "Opaque target id minted by get_browser_state.",
        "type": "string"
      },
      "to_x": {
        "description": "Drag destination viewport x in CSS pixels.",
        "type": "number"
      },
      "to_y": {
        "description": "Drag destination viewport y in CSS pixels.",
        "type": "number"
      },
      "x": {
        "description": "Origin viewport x in CSS pixels.",
        "type": "number"
      },
      "y": {
        "description": "Origin viewport y in CSS pixels.",
        "type": "number"
      }
    },
    "required": [
      "target_id",
      "tab_id",
      "session",
      "action"
    ],
    "type": "object"
  },
  "browser_prepare": {
    "additionalProperties": true,
    "properties": {
      "allow_launch": {
        "description": "Allow a separate driver-owned isolated Chromium process to be launched (default false).",
        "type": "boolean"
      },
      "pid": {
        "description": "Browser process id to prepare.",
        "type": "integer"
      },
      "profile": {
        "additionalProperties": false,
        "properties": {
          "mode": {
            "enum": [
              "isolated_new",
              "isolated_named"
            ],
            "type": "string"
          },
          "name": {
            "description": "Required only for isolated_named; 1-64 path-safe ASCII characters.",
            "type": "string"
          }
        },
        "required": [
          "mode"
        ],
        "type": "object"
      },
      "session": {
        "description": "For multi-call work, prefer a short public session label and repeat it on every call that accepts it.",
        "type": "string"
      },
      "strategy": {
        "additionalProperties": false,
        "properties": {
          "kind": {
            "enum": [
              "existing_profile"
            ],
            "type": "string"
          }
        },
        "required": [
          "kind"
        ],
        "type": "object"
      },
      "window_id": {
        "description": "Exact native window approval anchor; required for strategy.kind=existing_profile.",
        "type": "integer"
      }
    },
    "required": [],
    "type": "object"
  },
  "browser_set_input_files": {
    "additionalProperties": true,
    "properties": {
      "files": {
        "items": {
          "description": "Absolute path to one local regular file.",
          "type": "string"
        },
        "maxItems": 32,
        "minItems": 1,
        "type": "array"
      },
      "ref": {
        "description": "Page element ref in the p<snapshot>:<index> namespace from get_browser_state.",
        "type": "string"
      },
      "session": {
        "description": "For multi-call work, prefer a short public session label and repeat it on every call that accepts it.",
        "type": "string"
      },
      "tab_id": {
        "description": "Opaque tab id from get_browser_state (session-scoped).",
        "type": "string"
      },
      "target_id": {
        "description": "Opaque browser target id minted by get_browser_state (session-scoped; never a CDP id).",
        "type": "string"
      }
    },
    "required": [
      "target_id",
      "tab_id",
      "ref",
      "files"
    ],
    "type": "object"
  },
  "browser_type": {
    "additionalProperties": true,
    "properties": {
      "mode": {
        "description": "insert_text (default): bulk Input.insertText.",
        "enum": [
          "insert_text",
          "keystrokes"
        ],
        "type": "string"
      },
      "ref": {
        "description": "Page element ref in the p<snapshot>:<index> namespace from get_browser_state.",
        "type": "string"
      },
      "replace": {
        "description": "false (default): insert at the caret, appending to whatever the field already holds.",
        "type": "boolean"
      },
      "session": {
        "description": "For multi-call work, prefer a short public session label and repeat it on every call that accepts it.",
        "type": "string"
      },
      "tab_id": {
        "description": "Opaque tab id from get_browser_state (session-scoped).",
        "type": "string"
      },
      "target_id": {
        "description": "Opaque browser target id minted by get_browser_state (session-scoped; never a CDP id).",
        "type": "string"
      },
      "text": {
        "description": "Text to type.",
        "type": "string"
      }
    },
    "required": [
      "target_id",
      "tab_id",
      "ref",
      "text"
    ],
    "type": "object"
  },
  "check_for_update": {
    "additionalProperties": false,
    "properties": {},
    "type": "object"
  },
  "check_permissions": {
    "additionalProperties": false,
    "properties": {
      "probe_direct_capture": {
        "description": "When prompting and Screen Recording is granted, also run the live ScreenCaptureKit probe that may raise Tahoe's direct-capture consent.",
        "type": "boolean"
      },
      "prompt": {
        "default": false,
        "description": "Raise the system permission prompts for missing grants.",
        "type": "boolean"
      }
    },
    "type": "object"
  },
  "click": {
    "additionalProperties": false,
    "properties": {
      "action": {
        "description": "AX action: press, show_menu, pick, confirm, cancel, open.",
        "type": "string"
      },
      "button": {
        "description": "Mouse button.",
        "enum": [
          "left",
          "right",
          "middle"
        ],
        "type": "string"
      },
      "count": {
        "description": "Click count (pixel path only).",
        "type": "integer"
      },
      "debug_image_out": {
        "description": "Optional file path.",
        "type": "string"
      },
      "delivery_mode": {
        "description": "Best-effort-background ladder rung (default \"background\").",
        "enum": [
          "background",
          "foreground"
        ],
        "type": "string"
      },
      "element_index": {
        "description": "Element index from get_window_state.",
        "type": "integer"
      },
      "element_token": {
        "description": "Opaque per-snapshot element handle from `structuredContent.elements[].element_token`.",
        "type": "string"
      },
      "from_zoom": {
        "description": "When true, x and y are in the last zoom image for this pid; driver translates back to full-window coordinates.",
        "type": "boolean"
      },
      "modifier": {
        "description": "Modifier keys: cmd, shift, option/alt, ctrl.",
        "items": {
          "type": "string"
        },
        "type": "array"
      },
      "pid": {
        "description": "Target process ID.",
        "type": "integer"
      },
      "scope": {
        "description": "Coordinate frame for a windowless screen-absolute click (default \"window\").",
        "enum": [
          "window",
          "desktop"
        ],
        "type": "string"
      },
      "session": {
        "description": "For multi-call work, prefer a short public session label and repeat it on every call that accepts it.",
        "type": "string"
      },
      "snapshot_id": {
        "description": "Snapshot handle from get_window_state.",
        "pattern": "^s[0-9a-f]{8}$",
        "type": "string"
      },
      "target": {
        "description": "Exact capture/input target selected independently for each action.",
        "oneOf": [
          {
            "additionalProperties": true,
            "properties": {
              "kind": {
                "const": "window",
                "type": "string"
              },
              "pid": {
                "format": "uint32",
                "minimum": 0,
                "type": "integer"
              },
              "window_id": {
                "format": "uint64",
                "minimum": 0,
                "type": "integer"
              }
            },
            "required": [
              "kind",
              "pid",
              "window_id"
            ],
            "type": "object"
          },
          {
            "additionalProperties": true,
            "properties": {
              "display_id": {
                "type": "string"
              },
              "kind": {
                "const": "desktop",
                "type": "string"
              }
            },
            "required": [
              "kind",
              "display_id"
            ],
            "type": "object"
          }
        ]
      },
      "window_id": {
        "description": "Target window ID.",
        "type": "integer"
      },
      "x": {
        "description": "X in screenshot pixels.",
        "type": "number"
      },
      "y": {
        "description": "Y in screenshot pixels from the image selected by target.",
        "type": "number"
      }
    },
    "required": [],
    "type": "object"
  },
  "clipboard_read": {
    "additionalProperties": false,
    "properties": {
      "include_text": {
        "default": false,
        "description": "Return plain-text clipboard content in addition to the available types.",
        "type": "boolean"
      },
      "session": {
        "description": "For multi-call work, prefer a short public session label and repeat it on every call that accepts it.",
        "type": "string"
      }
    },
    "required": [],
    "type": "object"
  },
  "clipboard_write": {
    "additionalProperties": false,
    "properties": {
      "file_path": {
        "description": "Absolute path to a local file to place on the clipboard as a file URL.",
        "type": "string"
      },
      "image_path": {
        "description": "Absolute path to a local image to place on the clipboard.",
        "type": "string"
      },
      "session": {
        "description": "For multi-call work, prefer a short public session label and repeat it on every call that accepts it.",
        "type": "string"
      },
      "text": {
        "description": "Plain text to place on the clipboard.",
        "type": "string"
      }
    },
    "required": [],
    "type": "object"
  },
  "double_click": {
    "additionalProperties": false,
    "properties": {
      "delivery_mode": {
        "description": "Best-effort-background ladder rung (default \"background\").",
        "enum": [
          "background",
          "foreground"
        ],
        "type": "string"
      },
      "element_index": {
        "description": "Element index from get_window_state.",
        "type": "integer"
      },
      "element_token": {
        "description": "Opaque per-snapshot element handle from `structuredContent.elements[].element_token`.",
        "type": "string"
      },
      "pid": {
        "type": "integer"
      },
      "session": {
        "description": "For multi-call work, prefer a short public session label and repeat it on every call that accepts it.",
        "type": "string"
      },
      "snapshot_id": {
        "description": "Snapshot handle from get_window_state.",
        "pattern": "^s[0-9a-f]{8}$",
        "type": "string"
      },
      "window_id": {
        "description": "CGWindowID.",
        "type": "integer"
      },
      "x": {
        "description": "Screen X coordinate (pixel path).",
        "type": "number"
      },
      "y": {
        "description": "Screen Y coordinate (pixel path).",
        "type": "number"
      }
    },
    "required": [
      "pid"
    ],
    "type": "object"
  },
  "drag": {
    "additionalProperties": false,
    "properties": {
      "button": {
        "description": "Mouse button used for the drag.",
        "enum": [
          "left",
          "right",
          "middle"
        ],
        "type": "string"
      },
      "delivery_mode": {
        "description": "Best-effort-background ladder rung (default \"background\").",
        "enum": [
          "background",
          "foreground"
        ],
        "type": "string"
      },
      "duration_ms": {
        "description": "Wall-clock duration of the drag path between mouseDown and mouseUp.",
        "maximum": 10000,
        "minimum": 0,
        "type": "integer"
      },
      "from_x": {
        "description": "Drag-start X in window-local screenshot pixels.",
        "type": "number"
      },
      "from_y": {
        "description": "Drag-start Y in window-local screenshot pixels.",
        "type": "number"
      },
      "from_zoom": {
        "description": "When true, coordinates are in the last zoom image for this pid; driver maps back to window coordinates.",
        "type": "boolean"
      },
      "modifier": {
        "description": "Modifier keys held across the entire gesture: cmd/shift/option/ctrl.",
        "items": {
          "type": "string"
        },
        "type": "array"
      },
      "pid": {
        "description": "Target process ID.",
        "type": "integer"
      },
      "scope": {
        "default": "window",
        "description": "Use desktop with no pid/window_id for native get_desktop_state screenshot coordinates.",
        "enum": [
          "window",
          "desktop"
        ],
        "type": "string"
      },
      "session": {
        "description": "For multi-call work, prefer a short public session label and repeat it on every call that accepts it.",
        "type": "string"
      },
      "steps": {
        "description": "Number of intermediate mouseDragged events linearly interpolated along the path.",
        "maximum": 200,
        "minimum": 1,
        "type": "integer"
      },
      "target": {
        "anyOf": [
          {
            "description": "Exact capture/input target selected independently for each action.",
            "oneOf": [
              {
                "additionalProperties": true,
                "properties": {
                  "kind": {
                    "const": "window",
                    "type": "string"
                  },
                  "pid": {
                    "format": "uint32",
                    "minimum": 0,
                    "type": "integer"
                  },
                  "window_id": {
                    "format": "uint64",
                    "minimum": 0,
                    "type": "integer"
                  }
                },
                "required": [
                  "kind",
                  "pid",
                  "window_id"
                ],
                "type": "object"
              },
              {
                "additionalProperties": true,
                "properties": {
                  "display_id": {
                    "type": "string"
                  },
                  "kind": {
                    "const": "desktop",
                    "type": "string"
                  }
                },
                "required": [
                  "kind",
                  "display_id"
                ],
                "type": "object"
              }
            ]
          },
          {
            "type": "null"
          }
        ]
      },
      "to_x": {
        "description": "Drag-end X in window-local screenshot pixels.",
        "type": "number"
      },
      "to_y": {
        "description": "Drag-end Y in window-local screenshot pixels.",
        "type": "number"
      },
      "window_id": {
        "description": "CGWindowID for the window the pixel coordinates were measured against.",
        "type": "integer"
      }
    },
    "required": [
      "from_x",
      "from_y",
      "to_x",
      "to_y"
    ],
    "type": "object"
  },
  "end_session": {
    "additionalProperties": true,
    "properties": {
      "session": {
        "description": "Optional public label to end.",
        "type": "string"
      }
    },
    "required": [],
    "type": "object"
  },
  "escalate_session": {
    "additionalProperties": true,
    "properties": {
      "detail": {
        "description": "Optional bounded diagnostic detail.",
        "maxLength": 200,
        "type": "string"
      },
      "reason": {
        "enum": [
          "ax_tree_pixel_mismatch",
          "background_delivery_failed",
          "foreground_ineffective",
          "no_window_target",
          "other"
        ],
        "type": "string"
      },
      "session": {
        "type": "string"
      }
    },
    "required": [
      "session",
      "reason"
    ],
    "type": "object"
  },
  "get_accessibility_tree": {
    "additionalProperties": false,
    "properties": {},
    "type": "object"
  },
  "get_agent_cursor_state": {
    "additionalProperties": false,
    "properties": {
      "session": {
        "type": "string"
      }
    },
    "required": [
      "session"
    ],
    "type": "object"
  },
  "get_browser_state": {
    "additionalProperties": true,
    "properties": {
      "continuation": {
        "description": "Opaque continuation minted by an earlier semantic_v2 response.",
        "type": "string"
      },
      "include_screenshot": {
        "default": false,
        "description": "Capture the exact tab viewport as PNG through CDP without selecting the tab or foregrounding its native window.",
        "type": "boolean"
      },
      "pid": {
        "description": "Native browser process id (bind mode).",
        "type": "integer"
      },
      "query": {
        "description": "Read-only semantic match over role, accessible name, and visible text.",
        "type": "string"
      },
      "scope_ref": {
        "description": "Current semantic/content ref whose subtree should be observed.",
        "type": "string"
      },
      "session": {
        "description": "For multi-call work, prefer a short public session label and repeat it on every call that accepts it.",
        "type": "string"
      },
      "snapshot_format": {
        "description": "Versioned snapshot contract.",
        "enum": [
          "dom_refs_v1",
          "semantic_v2"
        ],
        "type": "string"
      },
      "tab_id": {
        "description": "Opaque tab id from get_browser_state (session-scoped).",
        "type": "string"
      },
      "target_id": {
        "description": "Opaque browser target id minted by get_browser_state (session-scoped; never a CDP id).",
        "type": "string"
      },
      "window_id": {
        "description": "Native window id owned by pid (bind mode).",
        "type": "integer"
      }
    },
    "type": "object"
  },
  "get_config": {
    "additionalProperties": false,
    "properties": {},
    "type": "object"
  },
  "get_cursor_position": {
    "additionalProperties": false,
    "properties": {
      "session": {
        "description": "For multi-call work, prefer a short public session label and repeat it on every call that accepts it.",
        "type": "string"
      }
    },
    "type": "object"
  },
  "get_desktop_state": {
    "additionalProperties": false,
    "properties": {
      "screenshot_out_file": {
        "description": "Write PNG here instead of base64.",
        "type": "string"
      },
      "session": {
        "description": "For multi-call work, prefer a short public session label and repeat it on every call that accepts it.",
        "type": "string"
      }
    },
    "type": "object"
  },
  "get_recording_state": {
    "additionalProperties": false,
    "properties": {},
    "type": "object"
  },
  "get_screen_size": {
    "additionalProperties": false,
    "properties": {
      "session": {
        "description": "For multi-call work, prefer a short public session label and repeat it on every call that accepts it.",
        "type": "string"
      }
    },
    "type": "object"
  },
  "get_session": {
    "additionalProperties": true,
    "properties": {
      "session": {
        "description": "Optional public label.",
        "type": "string"
      }
    },
    "required": [],
    "type": "object"
  },
  "get_session_state": {
    "additionalProperties": true,
    "properties": {
      "session": {
        "description": "Optional public label.",
        "type": "string"
      }
    },
    "required": [],
    "type": "object"
  },
  "get_window_state": {
    "additionalProperties": false,
    "properties": {
      "capture_mode": {
        "description": "DEPRECATED and ignored.",
        "enum": [
          "ax",
          "vision"
        ],
        "type": "string"
      },
      "include_accessibility_tree": {
        "description": "Default true — walk the AX tree and return `elements` + `tree_markdown` alongside the screenshot.",
        "type": "boolean"
      },
      "include_screenshot": {
        "description": "Default true — returns a grounding screenshot alongside the tree.",
        "type": "boolean"
      },
      "max_depth": {
        "description": "Cap on the AX-tree walk depth.",
        "minimum": 1,
        "type": "integer"
      },
      "max_dimension": {
        "description": "Optional cap on the returned screenshot's long edge, in pixels (aspect ratio preserved) — the cheap path for a small preview / thumbnail.",
        "minimum": 1,
        "type": "integer"
      },
      "max_elements": {
        "description": "Cap on the total number of AX nodes walked.",
        "minimum": 1,
        "type": "integer"
      },
      "pid": {
        "description": "Target process ID.",
        "type": "integer"
      },
      "query": {
        "description": "Case-insensitive filter for tree_markdown and structured elements.",
        "type": "string"
      },
      "screenshot_out_file": {
        "description": "When set, write the PNG to this file path (~ expanded) instead of embedding base64 in the response.",
        "type": "string"
      },
      "session": {
        "description": "For multi-call work, prefer a short public session label and repeat it on every call that accepts it.",
        "type": "string"
      },
      "window_id": {
        "description": "Target window ID from list_windows.",
        "type": "integer"
      }
    },
    "required": [
      "pid",
      "window_id"
    ],
    "type": "object"
  },
  "health_report": {
    "additionalProperties": false,
    "properties": {
      "include": {
        "description": "Only run these checks (canonical names).",
        "items": {
          "type": "string"
        },
        "type": "array"
      },
      "skip": {
        "description": "Skip these checks (canonical names).",
        "items": {
          "type": "string"
        },
        "type": "array"
      }
    },
    "type": "object"
  },
  "hotkey": {
    "additionalProperties": false,
    "properties": {
      "delivery_mode": {
        "description": "Best-effort-background ladder rung (default \"background\").",
        "enum": [
          "background",
          "foreground"
        ],
        "type": "string"
      },
      "element_index": {
        "description": "Element index from get_window_state.",
        "type": "integer"
      },
      "element_token": {
        "description": "Opaque per-snapshot element handle from `structuredContent.elements[].element_token`.",
        "type": "string"
      },
      "keys": {
        "description": "Modifier(s) and one non-modifier key, e.g.",
        "items": {
          "type": "string"
        },
        "minItems": 2,
        "type": "array"
      },
      "pid": {
        "description": "Target process ID.",
        "type": "integer"
      },
      "scope": {
        "default": "window",
        "description": "Use desktop with no pid/window_id to send the chord to the frontmost application.",
        "enum": [
          "window",
          "desktop"
        ],
        "type": "string"
      },
      "session": {
        "description": "For multi-call work, prefer a short public session label and repeat it on every call that accepts it.",
        "type": "string"
      },
      "snapshot_id": {
        "description": "Snapshot handle from get_window_state.",
        "pattern": "^s[0-9a-f]{8}$",
        "type": "string"
      },
      "target": {
        "anyOf": [
          {
            "description": "Exact capture/input target selected independently for each action.",
            "oneOf": [
              {
                "additionalProperties": true,
                "properties": {
                  "kind": {
                    "const": "window",
                    "type": "string"
                  },
                  "pid": {
                    "format": "uint32",
                    "minimum": 0,
                    "type": "integer"
                  },
                  "window_id": {
                    "format": "uint64",
                    "minimum": 0,
                    "type": "integer"
                  }
                },
                "required": [
                  "kind",
                  "pid",
                  "window_id"
                ],
                "type": "object"
              },
              {
                "additionalProperties": true,
                "properties": {
                  "display_id": {
                    "type": "string"
                  },
                  "kind": {
                    "const": "desktop",
                    "type": "string"
                  }
                },
                "required": [
                  "kind",
                  "display_id"
                ],
                "type": "object"
              }
            ]
          },
          {
            "type": "null"
          }
        ]
      },
      "window_id": {
        "description": "Target window.",
        "type": "integer"
      },
      "x": {
        "description": "Screenshot-pixel X — the element px action form: pixel-click there to focus, then send the combo (so e.g.",
        "type": "number"
      },
      "y": {
        "description": "Screenshot-pixel Y (see x).",
        "type": "number"
      }
    },
    "required": [
      "keys"
    ],
    "type": "object"
  },
  "install_ffmpeg": {
    "additionalProperties": false,
    "properties": {
      "confirm": {
        "description": "Run the install command.",
        "type": "boolean"
      }
    },
    "type": "object"
  },
  "invoke_menu": {
    "additionalProperties": false,
    "description": "Exact, immediate-child application menu path to resolve and invoke through the operating system's accessibility API.",
    "properties": {
      "path": {
        "items": {
          "maxLength": 200,
          "minLength": 1,
          "type": "string"
        },
        "maxItems": 16,
        "minItems": 1,
        "type": "array"
      },
      "pid": {
        "minimum": 1,
        "type": "integer"
      },
      "session": {
        "description": "For multi-call work, prefer a short public session label and repeat it on every call that accepts it.",
        "type": "string"
      },
      "window_id": {
        "minimum": 1,
        "type": "integer"
      }
    },
    "required": [
      "pid",
      "window_id",
      "path"
    ],
    "type": "object"
  },
  "kill_app": {
    "additionalProperties": false,
    "properties": {
      "pid": {
        "description": "PID of the process to terminate.",
        "type": "integer"
      }
    },
    "required": [
      "pid"
    ],
    "type": "object"
  },
  "launch_app": {
    "additionalProperties": false,
    "properties": {
      "additional_arguments": {
        "description": "Extra arguments appended after --args when launching.",
        "items": {
          "type": "string"
        },
        "type": "array"
      },
      "bundle_id": {
        "description": "App bundle identifier, e.g.",
        "type": "string"
      },
      "creates_new_application_instance": {
        "description": "When true, force a new app instance even if already running (open -n).",
        "type": "boolean"
      },
      "name": {
        "description": "App display name.",
        "type": "string"
      },
      "urls": {
        "description": "Optional file paths or URLs to open with the app (e.g.",
        "items": {
          "type": "string"
        },
        "type": "array"
      },
      "webkit_inspector_port": {
        "description": "Open a WebKit inspector server on this port (sets WEBKIT_INSPECTOR_SERVER env var).",
        "type": "integer"
      }
    },
    "type": "object"
  },
  "list_apps": {
    "additionalProperties": false,
    "properties": {},
    "type": "object"
  },
  "list_sessions": {
    "additionalProperties": true,
    "properties": {
      "cursor": {
        "description": "Opaque continuation cursor returned by a previous call.",
        "type": "string"
      },
      "limit": {
        "description": "Maximum number of content-free summaries to return (default 50, max 100).",
        "format": "uint32",
        "minimum": 0,
        "type": [
          "integer",
          "null"
        ]
      }
    },
    "required": [],
    "type": "object"
  },
  "list_windows": {
    "additionalProperties": false,
    "properties": {
      "on_screen_only": {
        "description": "When true, drop windows not on the current Space.",
        "type": "boolean"
      },
      "pid": {
        "description": "Optional pid filter.",
        "type": "integer"
      }
    },
    "type": "object"
  },
  "move_cursor": {
    "additionalProperties": false,
    "properties": {
      "cursor_id": {
        "description": "Cursor instance to move.",
        "type": "string"
      },
      "scope": {
        "default": "window",
        "enum": [
          "window",
          "desktop"
        ],
        "type": "string"
      },
      "session": {
        "description": "For multi-call work, prefer a short public session label and repeat it on every call that accepts it.",
        "type": "string"
      },
      "target": {
        "anyOf": [
          {
            "description": "Exact capture/input target selected independently for each action.",
            "oneOf": [
              {
                "additionalProperties": true,
                "properties": {
                  "kind": {
                    "const": "window",
                    "type": "string"
                  },
                  "pid": {
                    "format": "uint32",
                    "minimum": 0,
                    "type": "integer"
                  },
                  "window_id": {
                    "format": "uint64",
                    "minimum": 0,
                    "type": "integer"
                  }
                },
                "required": [
                  "kind",
                  "pid",
                  "window_id"
                ],
                "type": "object"
              },
              {
                "additionalProperties": true,
                "properties": {
                  "display_id": {
                    "type": "string"
                  },
                  "kind": {
                    "const": "desktop",
                    "type": "string"
                  }
                },
                "required": [
                  "kind",
                  "display_id"
                ],
                "type": "object"
              }
            ]
          },
          {
            "type": "null"
          }
        ],
        "description": "Preferred per-call target."
      },
      "x": {
        "type": "number"
      },
      "y": {
        "type": "number"
      }
    },
    "required": [
      "x",
      "y"
    ],
    "type": "object"
  },
  "page": {
    "additionalProperties": false,
    "properties": {
      "action": {
        "description": "Action to perform.",
        "enum": [
          "execute_javascript",
          "get_text",
          "query_dom",
          "click_element",
          "insert_text",
          "type_keystrokes",
          "enable_javascript_apple_events"
        ],
        "type": "string"
      },
      "attributes": {
        "description": "Element attributes to include in query_dom results.",
        "items": {
          "type": "string"
        },
        "type": "array"
      },
      "bundle_id": {
        "description": "Bundle ID of the browser.",
        "type": "string"
      },
      "cdp_port": {
        "description": "Optional, for execute_javascript/insert_text/type_keystrokes: use this exact CDP port instead of auto-discovering one from pid.",
        "maximum": 65535,
        "minimum": 1,
        "type": "integer"
      },
      "css_selector": {
        "description": "CSS selector for query_dom (e.g.",
        "type": "string"
      },
      "javascript": {
        "description": "JavaScript to execute.",
        "type": "string"
      },
      "pid": {
        "description": "Target process ID.",
        "type": "integer"
      },
      "selector": {
        "description": "CSS selector for click_element (e.g.",
        "type": "string"
      },
      "target_url_contains": {
        "description": "Optional, for execute_javascript/insert_text/type_keystrokes: require exactly one browser tab whose URL contains this substring.",
        "type": "string"
      },
      "text": {
        "description": "Text to insert or type.",
        "type": "string"
      },
      "user_has_confirmed_enabling": {
        "description": "Must be true to proceed with enable_javascript_apple_events.",
        "type": "boolean"
      },
      "window_id": {
        "description": "Target window ID from list_windows.",
        "type": "integer"
      }
    },
    "required": [
      "action"
    ],
    "type": "object"
  },
  "press_key": {
    "additionalProperties": false,
    "properties": {
      "delivery_mode": {
        "description": "Best-effort-background ladder rung (default \"background\").",
        "enum": [
          "background",
          "foreground"
        ],
        "type": "string"
      },
      "element_index": {
        "description": "Element index from get_window_state.",
        "type": "integer"
      },
      "element_token": {
        "description": "Opaque per-snapshot element handle from `structuredContent.elements[].element_token`.",
        "type": "string"
      },
      "key": {
        "description": "Key name: return, tab, escape, up, down, etc.",
        "type": "string"
      },
      "modifiers": {
        "description": "Modifier keys: cmd, shift, option/alt, ctrl, fn.",
        "items": {
          "type": "string"
        },
        "type": "array"
      },
      "pid": {
        "type": "integer"
      },
      "scope": {
        "default": "window",
        "description": "Use desktop with no pid/window_id to send the key to the frontmost application.",
        "enum": [
          "window",
          "desktop"
        ],
        "type": "string"
      },
      "session": {
        "description": "For multi-call work, prefer a short public session label and repeat it on every call that accepts it.",
        "type": "string"
      },
      "snapshot_id": {
        "description": "Snapshot handle from get_window_state.",
        "pattern": "^s[0-9a-f]{8}$",
        "type": "string"
      },
      "target": {
        "anyOf": [
          {
            "description": "Exact capture/input target selected independently for each action.",
            "oneOf": [
              {
                "additionalProperties": true,
                "properties": {
                  "kind": {
                    "const": "window",
                    "type": "string"
                  },
                  "pid": {
                    "format": "uint32",
                    "minimum": 0,
                    "type": "integer"
                  },
                  "window_id": {
                    "format": "uint64",
                    "minimum": 0,
                    "type": "integer"
                  }
                },
                "required": [
                  "kind",
                  "pid",
                  "window_id"
                ],
                "type": "object"
              },
              {
                "additionalProperties": true,
                "properties": {
                  "display_id": {
                    "type": "string"
                  },
                  "kind": {
                    "const": "desktop",
                    "type": "string"
                  }
                },
                "required": [
                  "kind",
                  "display_id"
                ],
                "type": "object"
              }
            ]
          },
          {
            "type": "null"
          }
        ]
      },
      "window_id": {
        "description": "Target window.",
        "type": "integer"
      },
      "x": {
        "description": "Screenshot-pixel X — the element px action form: pixel-click there to focus, then send the key.",
        "type": "number"
      },
      "y": {
        "description": "Screenshot-pixel Y (see x).",
        "type": "number"
      }
    },
    "required": [
      "key"
    ],
    "type": "object"
  },
  "replay_trajectory": {
    "additionalProperties": false,
    "properties": {
      "delay_ms": {
        "description": "Milliseconds to sleep between turns, for human-observable pacing.",
        "maximum": 10000,
        "minimum": 0,
        "type": "integer"
      },
      "dir": {
        "description": "Trajectory directory previously written by `start_recording`.",
        "type": "string"
      },
      "stop_on_error": {
        "description": "Stop replay on the first tool-call error.",
        "type": "boolean"
      }
    },
    "required": [
      "dir"
    ],
    "type": "object"
  },
  "right_click": {
    "additionalProperties": false,
    "properties": {
      "delivery_mode": {
        "description": "Best-effort-background ladder rung (default \"background\").",
        "enum": [
          "background",
          "foreground"
        ],
        "type": "string"
      },
      "element_index": {
        "description": "Element index from get_window_state.",
        "type": "integer"
      },
      "element_token": {
        "description": "Opaque per-snapshot element handle from `structuredContent.elements[].element_token`.",
        "type": "string"
      },
      "modifier": {
        "description": "Modifier keys held during the right-click: cmd/shift/option/ctrl.",
        "items": {
          "type": "string"
        },
        "type": "array"
      },
      "pid": {
        "description": "Target process ID.",
        "type": "integer"
      },
      "session": {
        "description": "For multi-call work, prefer a short public session label and repeat it on every call that accepts it.",
        "type": "string"
      },
      "snapshot_id": {
        "description": "Snapshot handle from get_window_state.",
        "pattern": "^s[0-9a-f]{8}$",
        "type": "string"
      },
      "window_id": {
        "description": "CGWindowID.",
        "type": "integer"
      },
      "x": {
        "description": "X in window-local screenshot pixels.",
        "type": "number"
      },
      "y": {
        "description": "Y in window-local screenshot pixels.",
        "type": "number"
      }
    },
    "required": [
      "pid"
    ],
    "type": "object"
  },
  "scroll": {
    "additionalProperties": false,
    "properties": {
      "amount": {
        "description": "Pixel-wheel path: number of wheel notches.",
        "maximum": 50,
        "minimum": 1,
        "type": "integer"
      },
      "by": {
        "description": "Scroll granularity.",
        "enum": [
          "line",
          "page"
        ],
        "type": "string"
      },
      "delivery_mode": {
        "description": "Best-effort-background ladder rung (default \"background\").",
        "enum": [
          "background",
          "foreground"
        ],
        "type": "string"
      },
      "direction": {
        "description": "Scroll direction.",
        "enum": [
          "up",
          "down",
          "left",
          "right"
        ],
        "type": "string"
      },
      "element_index": {
        "description": "Element index from get_window_state.",
        "type": "integer"
      },
      "element_token": {
        "description": "Opaque per-snapshot element handle from `structuredContent.elements[].element_token`.",
        "type": "string"
      },
      "pid": {
        "type": "integer"
      },
      "scope": {
        "default": "window",
        "description": "Use desktop with x,y and no pid/window_id for native get_desktop_state screenshot coordinates.",
        "enum": [
          "window",
          "desktop"
        ],
        "type": "string"
      },
      "session": {
        "description": "For multi-call work, prefer a short public session label and repeat it on every call that accepts it.",
        "type": "string"
      },
      "snapshot_id": {
        "description": "Snapshot handle from get_window_state.",
        "pattern": "^s[0-9a-f]{8}$",
        "type": "string"
      },
      "target": {
        "anyOf": [
          {
            "description": "Exact capture/input target selected independently for each action.",
            "oneOf": [
              {
                "additionalProperties": true,
                "properties": {
                  "kind": {
                    "const": "window",
                    "type": "string"
                  },
                  "pid": {
                    "format": "uint32",
                    "minimum": 0,
                    "type": "integer"
                  },
                  "window_id": {
                    "format": "uint64",
                    "minimum": 0,
                    "type": "integer"
                  }
                },
                "required": [
                  "kind",
                  "pid",
                  "window_id"
                ],
                "type": "object"
              },
              {
                "additionalProperties": true,
                "properties": {
                  "display_id": {
                    "type": "string"
                  },
                  "kind": {
                    "const": "desktop",
                    "type": "string"
                  }
                },
                "required": [
                  "kind",
                  "display_id"
                ],
                "type": "object"
              }
            ]
          },
          {
            "type": "null"
          }
        ]
      },
      "window_id": {
        "type": "integer"
      },
      "x": {
        "description": "Window-local screenshot X (top-left origin of the PNG from get_window_state).",
        "type": "number"
      },
      "y": {
        "description": "Window-local screenshot Y.",
        "type": "number"
      }
    },
    "required": [
      "direction"
    ],
    "type": "object"
  },
  "set_agent_cursor_enabled": {
    "additionalProperties": false,
    "properties": {
      "enabled": {
        "type": "boolean"
      },
      "session": {
        "type": "string"
      }
    },
    "required": [
      "session",
      "enabled"
    ],
    "type": "object"
  },
  "set_agent_cursor_motion": {
    "additionalProperties": false,
    "properties": {
      "arc_flow": {
        "format": "double",
        "type": [
          "number",
          "null"
        ]
      },
      "arc_size": {
        "format": "double",
        "type": [
          "number",
          "null"
        ]
      },
      "dwell_after_click_ms": {
        "format": "double",
        "type": [
          "number",
          "null"
        ]
      },
      "end_handle": {
        "format": "double",
        "type": [
          "number",
          "null"
        ]
      },
      "glide_duration_ms": {
        "format": "double",
        "type": [
          "number",
          "null"
        ]
      },
      "idle_hide_ms": {
        "format": "double",
        "type": [
          "number",
          "null"
        ]
      },
      "session": {
        "type": "string"
      },
      "spring": {
        "format": "double",
        "type": [
          "number",
          "null"
        ]
      },
      "start_handle": {
        "format": "double",
        "type": [
          "number",
          "null"
        ]
      },
      "turn_radius": {
        "format": "double",
        "type": [
          "number",
          "null"
        ]
      }
    },
    "required": [
      "session"
    ],
    "type": "object"
  },
  "set_agent_cursor_theme": {
    "additionalProperties": false,
    "properties": {
      "reduced_motion": {
        "default": "auto",
        "enum": [
          "auto",
          "on",
          "off"
        ],
        "type": "string"
      },
      "session": {
        "type": "string"
      },
      "theme_id": {
        "maxLength": 200,
        "minLength": 1,
        "type": "string"
      }
    },
    "required": [
      "session",
      "theme_id"
    ],
    "type": "object"
  },
  "set_config": {
    "additionalProperties": false,
    "properties": {
      "experimental_pip": {
        "description": "Enable the experimental picture-in-picture preview window.",
        "type": "boolean"
      },
      "experimental_pip_geometry": {
        "description": "PiP window size + optional position in `WxH` or `WxH+X+Y` form (e.g.",
        "type": "string"
      },
      "key": {
        "description": "Name of a single config field to write ({key, value} shape, matching the CLI `config set` and the Windows/Linux tools).",
        "type": "string"
      },
      "max_image_dimension": {
        "description": "Max dimension for screenshot resizing (0 = no limit).",
        "type": "integer"
      },
      "value": {
        "description": "New value for `key`."
      }
    },
    "type": "object"
  },
  "set_value": {
    "additionalProperties": false,
    "properties": {
      "element_index": {
        "description": "Element index from get_window_state.",
        "type": "integer"
      },
      "element_token": {
        "description": "Opaque per-snapshot element handle from `structuredContent.elements[].element_token`.",
        "type": "string"
      },
      "pid": {
        "type": "integer"
      },
      "session": {
        "description": "For multi-call work, prefer a short public session label and repeat it on every call that accepts it.",
        "type": "string"
      },
      "snapshot_id": {
        "description": "Snapshot handle from get_window_state.",
        "pattern": "^s[0-9a-f]{8}$",
        "type": "string"
      },
      "value": {
        "description": "New value.",
        "type": "string"
      },
      "window_id": {
        "description": "CGWindowID for the window whose get_window_state produced the element_index.",
        "type": "integer"
      }
    },
    "required": [
      "pid",
      "value"
    ],
    "type": "object"
  },
  "set_window_frame": {
    "additionalProperties": false,
    "properties": {
      "height": {
        "minimum": 1,
        "type": "number"
      },
      "pid": {
        "minimum": 1,
        "type": "integer"
      },
      "session": {
        "description": "For multi-call work, prefer a short public session label and repeat it on every call that accepts it.",
        "type": "string"
      },
      "width": {
        "minimum": 1,
        "type": "number"
      },
      "window_id": {
        "minimum": 1,
        "type": "integer"
      },
      "x": {
        "type": "number"
      },
      "y": {
        "type": "number"
      }
    },
    "required": [
      "pid",
      "window_id",
      "x",
      "y",
      "width",
      "height"
    ],
    "type": "object"
  },
  "start_recording": {
    "additionalProperties": false,
    "properties": {
      "output_dir": {
        "description": "Absolute or ~-rooted directory where turn folders and (when enabled) the video file are written.",
        "type": "string"
      },
      "record_video": {
        "description": "Capture the main display to <output_dir>/recording.mp4.",
        "type": "boolean"
      }
    },
    "required": [
      "output_dir"
    ],
    "type": "object"
  },
  "start_session": {
    "additionalProperties": true,
    "properties": {
      "capture_scope": {
        "description": "Deprecated compatibility policy.",
        "enum": [
          "auto",
          "window",
          "desktop"
        ],
        "type": "string"
      },
      "cursor_theme": {
        "description": "Optional initial cursor theme.",
        "properties": {
          "reduced_motion": {
            "default": "auto",
            "enum": [
              "auto",
              "on",
              "off"
            ],
            "type": "string"
          },
          "theme_id": {
            "type": "string"
          }
        },
        "required": [
          "theme_id"
        ],
        "type": [
          "object",
          "null"
        ]
      },
      "session": {
        "description": "Optional stable public label for this run (e.g.",
        "type": "string"
      }
    },
    "required": [],
    "type": "object"
  },
  "stop_recording": {
    "additionalProperties": false,
    "properties": {},
    "type": "object"
  },
  "type_text": {
    "additionalProperties": false,
    "properties": {
      "delay_ms": {
        "description": "Milliseconds between characters in the CGEvent fallback path.",
        "maximum": 200,
        "minimum": 0,
        "type": "integer"
      },
      "delivery_mode": {
        "description": "Best-effort-background ladder rung (default \"background\").",
        "enum": [
          "background",
          "foreground"
        ],
        "type": "string"
      },
      "element_index": {
        "description": "Element index from get_window_state.",
        "type": "integer"
      },
      "element_token": {
        "description": "Opaque per-snapshot element handle from `structuredContent.elements[].element_token`.",
        "type": "string"
      },
      "pid": {
        "description": "Target process ID.",
        "type": "integer"
      },
      "scope": {
        "default": "window",
        "description": "Use desktop with no pid/window_id to type into the frontmost application.",
        "enum": [
          "window",
          "desktop"
        ],
        "type": "string"
      },
      "session": {
        "description": "For multi-call work, prefer a short public session label and repeat it on every call that accepts it.",
        "type": "string"
      },
      "snapshot_id": {
        "description": "Snapshot handle from get_window_state.",
        "pattern": "^s[0-9a-f]{8}$",
        "type": "string"
      },
      "target": {
        "anyOf": [
          {
            "description": "Exact capture/input target selected independently for each action.",
            "oneOf": [
              {
                "additionalProperties": true,
                "properties": {
                  "kind": {
                    "const": "window",
                    "type": "string"
                  },
                  "pid": {
                    "format": "uint32",
                    "minimum": 0,
                    "type": "integer"
                  },
                  "window_id": {
                    "format": "uint64",
                    "minimum": 0,
                    "type": "integer"
                  }
                },
                "required": [
                  "kind",
                  "pid",
                  "window_id"
                ],
                "type": "object"
              },
              {
                "additionalProperties": true,
                "properties": {
                  "display_id": {
                    "type": "string"
                  },
                  "kind": {
                    "const": "desktop",
                    "type": "string"
                  }
                },
                "required": [
                  "kind",
                  "display_id"
                ],
                "type": "object"
              }
            ]
          },
          {
            "type": "null"
          }
        ]
      },
      "text": {
        "description": "Text to insert at the target's cursor.",
        "type": "string"
      },
      "window_id": {
        "description": "CGWindowID.",
        "type": "integer"
      },
      "x": {
        "description": "Screenshot-pixel X of the field to type into — the element px action form.",
        "type": "number"
      },
      "y": {
        "description": "Screenshot-pixel Y of the field (see x).",
        "type": "number"
      }
    },
    "required": [
      "text"
    ],
    "type": "object"
  },
  "verify_state": {
    "additionalProperties": false,
    "properties": {
      "expect": {
        "description": "One to eight predicates, combined with logical AND.",
        "items": {
          "additionalProperties": false,
          "properties": {
            "element": {
              "additionalProperties": false,
              "properties": {
                "enabled": {
                  "type": [
                    "boolean",
                    "null"
                  ]
                },
                "exists": {
                  "description": "Assert that at least one trusted element matches the selector.",
                  "enum": [
                    true
                  ],
                  "type": "boolean"
                },
                "selected": {
                  "type": [
                    "boolean",
                    "null"
                  ]
                },
                "selector": {
                  "additionalProperties": false,
                  "properties": {
                    "label_contains": {
                      "minLength": 1,
                      "type": "string"
                    },
                    "role": {
                      "minLength": 1,
                      "type": "string"
                    }
                  },
                  "required": [],
                  "type": "object"
                },
                "value_equals": {
                  "type": [
                    "string",
                    "null"
                  ]
                }
              },
              "required": [
                "selector"
              ],
              "type": [
                "object",
                "null"
              ]
            },
            "window": {
              "additionalProperties": false,
              "properties": {
                "bounds": {
                  "additionalProperties": false,
                  "properties": {
                    "height": {
                      "type": "number"
                    },
                    "tolerance_px": {
                      "maximum": 100,
                      "minimum": 0,
                      "type": "number"
                    },
                    "width": {
                      "type": "number"
                    },
                    "x": {
                      "type": "number"
                    },
                    "y": {
                      "type": "number"
                    }
                  },
                  "required": [
                    "x",
                    "y",
                    "width",
                    "height"
                  ],
                  "type": [
                    "object",
                    "null"
                  ]
                },
                "exists": {
                  "type": [
                    "boolean",
                    "null"
                  ]
                }
              },
              "type": [
                "object",
                "null"
              ]
            }
          },
          "required": [],
          "type": "object"
        },
        "maxItems": 8,
        "minItems": 1,
        "type": "array"
      },
      "include_screenshot": {
        "description": "Return the final window screenshot as image content for a multimodal caller.",
        "type": [
          "boolean",
          "null"
        ]
      },
      "pid": {
        "description": "Exact process whose window may be observed.",
        "minimum": 1,
        "type": "integer"
      },
      "session": {
        "description": "For multi-call work, prefer a short public session label and repeat it on every call that accepts it.",
        "type": "string"
      },
      "stable_samples": {
        "default": 2,
        "description": "Consecutive satisfied samples required before returning success.",
        "maximum": 5,
        "minimum": 1,
        "type": "integer"
      },
      "timeout_ms": {
        "default": 5000,
        "description": "Bounded wait.",
        "maximum": 10000,
        "minimum": 0,
        "type": "integer"
      },
      "window_id": {
        "description": "Exact native window identifier.",
        "type": "integer"
      }
    },
    "required": [
      "pid",
      "window_id",
      "expect"
    ],
    "type": "object"
  },
  "zoom": {
    "additionalProperties": false,
    "properties": {
      "pid": {
        "description": "Target pid — required for from_zoom click/type translation.",
        "type": "integer"
      },
      "window_id": {
        "description": "CGWindowID from list_windows.",
        "type": "integer"
      },
      "x1": {
        "description": "Left edge of region in screenshot pixels.",
        "type": "number"
      },
      "x2": {
        "description": "Right edge of region in screenshot pixels.",
        "type": "number"
      },
      "y1": {
        "description": "Top edge of region in screenshot pixels.",
        "type": "number"
      },
      "y2": {
        "description": "Bottom edge of region in screenshot pixels.",
        "type": "number"
      }
    },
    "required": [
      "window_id",
      "x1",
      "y1",
      "x2",
      "y2"
    ],
    "type": "object"
  }
};
